name: PCB DevOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Output Folder
        run: mkdir -p outputs

      - name: Generate Gerber (Demo)
        run: echo "Gerber files generated" > outputs/gerber.txt

      - name: Generate BOM (Demo)
        run: echo "BOM generated" > outputs/bom.txt

      - name: Upload Files
        uses: actions/upload-artifact@v4
        with:
          name: pcb-output
          path: outputs/